export const SET_DEVICE = 'SET_DEVICE'
export const SET_SEARCH_SHOW = 'SET_SEARCH_SHOW'
export const SET_SEARCH_DEVICE = 'SET_SEARCH_DEVICE'
export const SET_ALL = 'SET_ALL'
export const SET_TOTAL = 'SET_TOTAL'
export const SET_CURPAGE = 'SET_CURPAGE'
export const SET_CURSIZE = 'SET_CURSIZE'